### ISSUE TITLE
Dependency on commons-codec missing

### ISSUE THREAD

**Issue by tarass** [elastic/elasticsearch-analysis-phonetic#40]
Doing upgrade to elasticsearch 1.5.1 and phonetic 2.5.0, I had an issue starting service because dependency on commons-codec is not automatically pulled in. After manually adding commons-codec 1.10 everything worked fine.

Specifically I used nysiis encoder and got this error:
java.lang.NoClassDefFoundError: org/apache/commons/codec/language/bm/NameType

**Comment by dadoonet** [comment]
Thank you for reporting this!
Could you give a script example which makes this error appear so I can reproduce and test the fix?

Thanks!

**Comment by tarass** [comment]
That happens when I pull in the module as a maven dependency into an embedded java project, as opposed to using the plugin installer.

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>1.5.2</version>
        </dependency>

    <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-analysis-phonetic</artifactId>
            <version>2.5.0</version>
        </dependency>

**Comment by dadoonet** [comment]
Then? How do you run this? I mean, do you run a unit test or something?

**Comment by tarass** [comment]
I don't have a small test for this ready. The elasticsearch node is started as part of a larger process then NYSIIS encoder is used which relies on the commons-codec.

If the test is ran where the plugin is loaded via installer everything is fine, since the dependency is mentioned here: https://github.com/elastic/elasticsearch-analysis-phonetic/blob/master/src/main/assemblies/plugin.xml

However, it is not mentioned in the base pom.xml: https://github.com/elastic/elasticsearch-analysis-phonetic/blob/master/pom.xml

**Comment by dadoonet** [comment]
It's a transitive dependency.

If you run `mvn dependency:tree`, you get:

```
[INFO] org.elasticsearch:elasticsearch-analysis-phonetic:jar:2.4.4-SNAPSHOT
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] +- com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.10:test
[INFO] |  \- junit:junit:jar:4.10:test
[INFO] +- org.apache.lucene:lucene-test-framework:jar:4.10.4:test
[INFO] |  +- org.apache.lucene:lucene-codecs:jar:4.10.4:test
[INFO] |  +- org.apache.lucene:lucene-core:jar:4.10.4:compile
[INFO] |  +- com.carrotsearch.randomizedtesting:junit4-ant:jar:2.1.6:test
[INFO] |  \- org.apache.ant:ant:jar:1.8.2:test
[INFO] +- org.elasticsearch:elasticsearch:jar:1.4.5:compile
[INFO] |  +- org.apache.lucene:lucene-analyzers-common:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-queries:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-memory:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-highlighter:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-queryparser:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-sandbox:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-suggest:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-misc:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-join:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-grouping:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-spatial:jar:4.10.4:compile
[INFO] |  |  \- com.spatial4j:spatial4j:jar:0.4.1:compile
[INFO] |  +- org.antlr:antlr-runtime:jar:3.5:compile
[INFO] |  +- org.ow2.asm:asm:jar:4.1:compile
[INFO] |  \- org.ow2.asm:asm-commons:jar:4.1:compile
[INFO] +- org.apache.lucene:lucene-analyzers-phonetic:jar:4.10.4:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] +- log4j:log4j:jar:1.2.16:runtime
[INFO] \- org.elasticsearch:elasticsearch:test-jar:tests:1.4.5:test
```

What gives the same command when you run it from your project?

BTW I checked that when you remove this line https://github.com/elastic/elasticsearch-analysis-phonetic/blob/master/src/main/assemblies/plugin.xml#L23, we still have as a dependency `commons-codec` lib in ZIP file. I will remove it.

I think that you have something wrong on your side. May be your project already set another version of this dependency. Could you check that?

**Comment by tarass** [comment]
You're right. It is looking like a version conflict. I was pulling in apache httpclient library that was dependent on codecs 1.6, causing something to not be happy.

[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.2:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.1:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.6:compile

**Comment by dadoonet** [comment]
I think we can close it. Feel free to reopen if needed.
